frontend/admin_app/urls.py
from django.urls import path
from . import views
app_name='admin_app'


urlpatterns=[
    path('base',views.base,name='base'),
    path('admin_dashboard/',views.admin_dashboard,name='admin_dashboard'),
    path('all_customers/',views.all_customers,name='all_customers'),
    path('add_description/',views.add_description,name='add_description'),
    path('view_destination/',views.view_destination,name='view_destination'),
    path('view_booking/',views.view_booking,name='view_booking'),
    path('view_queries/',views.view_queries,name='view_queries'),
    path('change_password/',views.change_password,name='change_password'),
]

frontend/common/urls.py
from django.urls import path
from . import views
app_name='common'


urlpatterns=[
    path('base',views.base,name='base'),
    path('',views.index,name='home'),
    path('blog',views.blog,name='blog'),
    path('view_blog',views.view_blog,name='view_blog'),
    path('aboutus',views.aboutus,name='about'),
    path('contactus',views.contactus,name='contact'),
    path('customer_register/',views.customer_register,name='customer_register'),
    path('customer_login/',views.customer_login,name='customer_login'),
    path('admin_register/',views.admin_register,name='admin_register'),
    path('admin_login/',views.admin_login,name='admin_login'),
]

frontend/customer_app/urls.py
from django.urls import path
from . import views

app_name='customer_app'

urlpatterns=[
    path('base/',views.base,name='base'),
]

frontend/frontend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('admin_app/', include('admin_app.urls')),
    path('customer_app/', include('customer_app.urls')),
    
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

frontend/admin_app/models.py
from django.db import models

# Create your models here.

frontend/common/models.py
from django.db import models

# Create your models here.

frontend/customer_app/models.py
from django.db import models

# Create your models here.

frontend/admin_app/views.py
from django.shortcuts import render

# Create your views here.
def base(request):
   return render(request,'admin_app_templates/base.html')

def admin_dashboard(request):
   return render(request,'admin_app_templates/admin_dashboard.html')

def all_customers(request):
   return render(request,'admin_app_templates/all_customers.html')

def add_description(request):
   return render(request,'admin_app_templates/add_description.html')

def view_destination(request):
   return render(request,'admin_app_templates/view_destination.html')

def view_booking(request):
   return render(request,'admin_app_templates/view_booking.html')

def view_queries(request):
   return render(request,'admin_app_templates/view_queries.html')

def change_password(request):
   return render(request,'admin_app_templates/change_password.html')

frontend/common/views.py
from django.shortcuts import render

# Create your views here.

def base(request):
   
    return render(request,'common_templates/base.html')

def index(request):
   
    return render(request,'common_templates/index.html')

def blog(request):
   
    return render(request,'common_templates/blog.html')

def view_blog(request):
   
    return render(request,'common_templates/view_blog.html')

def aboutus(request):
   
    return render(request,'common_templates/aboutus.html')

def contactus(request):
   
    return render(request,'common_templates/contactus.html')


def customer_register(request):
   
    return render(request,'common_templates/customer_register.html')

def customer_login(request):
   
    return render(request,'common_templates/customer_login.html')

# /////////////// ADMIN //////////////////////

def admin_register(request):
   
    return render(request,'common_templates/admin_register.html')


def admin_login(request):
   
    return render(request,'common_templates/admin_login.html')

frontend/customer_app/views.py
from django.shortcuts import render

# Create your views here.

def base(request):
    return render(request,'customer_app_templates/base.html')

frontend/admin_app/templates/admin_app_templates/add_description.html
{% extends 'admin_app_templates/base.html' %}
{% load static %}

{% block header %}

<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>





{% endblock %}

{% block title %}Add description{% endblock %}
{% block content %}

<!-- <section>
    <div class="container">
        <div class="row">
            <div class="col-md-12 mt-5">
                <h3>Add Description</h3>
                <button type="button" class="btn btn-secondary">Secondary</button>
            </div>
        </div>
    </div>
</section> -->

<section>
    <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-xl-9">

                <h1 class="mb-4 mt-5">Add Description</h1>

                <div class="card shadow-lg p-3 mb-5 bg-white rounded" style="border-radius: 15px;">
                    <div class="card-body">

                        <div class="row align-items-center pt-4 pb-3">
                            <div class="col-md-3 ps-5">

                                <h6 class="mb-0">Place</h6>

                            </div>
                            <div class="col-md-9 pe-5">

                                <input type="text" placeholder="Place" class="form-control form-control-lg" />

                            </div>
                        </div>

                        <hr class="mx-n3">

                        <div class="row align-items-center py-3">
                            <div class="col-md-3 ps-5">

                                <h6 class="mb-0">Country</h6>

                            </div>
                            <div class="col-md-9 pe-5">

                                <input type="email" class="form-control form-control-lg" placeholder="Country" />

                            </div>
                        </div>
                        <hr class="mx-n3">
                        <div class="row align-items-center py-3">
                            <div class="col-md-3 ps-5">

                                <h6 class="mb-0">Bus price</h6>

                            </div>
                            <div class="col-md-9 pe-5">

                                <input type="email" class="form-control form-control-lg" placeholder="Bus price" />

                            </div>
                        </div>

                        <hr class="mx-n3">
                        <div class="row align-items-center py-3">
                            <div class="col-md-3 ps-5">

                                <h6 class="mb-0">Train price</h6>

                            </div>
                            <div class="col-md-9 pe-5">

                                <input type="email" class="form-control form-control-lg" placeholder="Train price" />

                            </div>
                        </div>

                        <hr class="mx-n3">

                        <div class="row align-items-center py-3">
                            <div class="col-md-3 ps-5">

                                <h6 class="mb-0">Flight price</h6>

                            </div>
                            <div class="col-md-9 pe-5">

                                <input type="email" class="form-control form-control-lg" placeholder="Flight price" />

                            </div>
                        </div>

                        <hr class="mx-n3">

                        <div class="row align-items-center py-3">
                            <div class="col-md-3 ps-5">

                                <h6 class="mb-0">Images</h6>

                            </div>
                            <div class="col-md-9 pe-5">

                                <input class="form-control form-control-lg" id="formFileLg" type="file" />
                            </div>
                        </div>

                        <div class="row align-items-center py-3">
                            <div class="col-md-3 ps-5">

                                <h6 class="mb-0">Images 1</h6>

                            </div>
                            <div class="col-md-9 pe-5">

                                <input class="form-control form-control-lg" id="formFileLg" type="file" />
                            </div>
                        </div>

                        <div class="row align-items-center py-3">
                            <div class="col-md-3 ps-5">

                                <h6 class="mb-0">Images 2</h6>

                            </div>
                            <div class="col-md-9 pe-5">

                                <input class="form-control form-control-lg" id="formFileLg" type="file" />
                            </div>
                        </div>

                        <div class="row align-items-center py-3">
                            <div class="col-md-3 ps-5">

                                <h6 class="mb-0">Images 3</h6>

                            </div>
                            <div class="col-md-9 pe-5">

                                <input class="form-control form-control-lg" id="formFileLg" type="file" />
                            </div>
                        </div>

                        <hr class="mx-n3">

                        <div class="row align-items-center py-3">
                            <div class="col-md-3 ps-5">

                                <h6 class="mb-0">Food price</h6>

                            </div>
                            <div class="col-md-9 pe-5">

                                <input type="email" class="form-control form-control-lg" placeholder="Food price" />

                            </div>
                        </div>

                        <hr class="mx-n3">

                        <div class="row align-items-center py-3">
                            <div class="col-md-3 ps-5">

                                <h6 class="mb-0">Number of person</h6>

                            </div>
                            <div class="col-md-9 pe-5">

                                <input type="email" class="form-control form-control-lg"
                                    placeholder="Number of person" />

                            </div>
                        </div>

                        <hr class="mx-n3">

                        <div class="row align-items-center py-3">
                            <div class="col-md-3 ps-5">

                                <h6 class="mb-0">Days</h6>

                            </div>
                            <div class="col-md-9 pe-5">

                                <input type="email" class="form-control form-control-lg" placeholder="Days" />

                            </div>
                        </div>

                        <hr class="mx-n3">

                        <div class="row align-items-center py-3">
                            <div class="col-md-3 ps-5">

                                <h6 class="mb-0">Nights</h6>

                            </div>
                            <div class="col-md-9 pe-5">

                                <input type="email" class="form-control form-control-lg" placeholder="Nights" />

                            </div>
                        </div>

                        <hr class="mx-n3">

                        <div class="row align-items-center py-3">
                            <div class="col-md-3 ps-5">

                                <h6 class="mb-0">Description</h6>

                            </div>
                            <div class="col-md-9 pe-5">

                                <textarea class="form-control" rows="3" placeholder="Right description..."></textarea>

                            </div>
                        </div>

                        <hr class="mx-n3">

                        <div class="px-5 py-4">
                            <button type="submit" class="btn btn-primary btn-lg">Add Description</button>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
</section>


{% endblock %}

frontend/admin_app/templates/admin_app_templates/admin_dashboard.html
{% extends 'admin_app_templates/base.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/style_register.css' %}">
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>

<style>
    .card {
        /* margin-top: 50%; */
        padding: 25px;
        background-color: darksalmon;
        border: 2px solid black;
    }

    .number {
        font-weight: bold;
        font-size: 50px;
    }

    .heading {
        letter-spacing: 2px;
        font-weight: 700;
        color: brown;
    }

    .box {
        padding-top: 20px;
    }
</style>



{% endblock %}

{% block title %}Common Home{% endblock %}
{% block content %}

<section>
    <div class="container">
        <div class="row mt-5">
            <div class="col-lg-4 col-md-4 col-sm-12 box">
                <div class="card text-center">
                    <h1 class="number">4</h1>
                    <h5 class="heading">Total Destination</h5>

                </div>

            </div>
            <div class="col-lg-4 col-md-4 col-sm-12 box">
                <div class="card text-center">
                    <h1 class="number">4</h1>
                    <h5 class="heading">Total Booking</h5>

                </div>

            </div>
            <div class="col-lg-4 col-md-4 col-sm-12 box">
                <div class="card text-center">
                    <h1 class="number">4</h1>
                    <h5 class="heading">Total User</h5>

                </div>

            </div>
        </div>
    </div>
</section>


{% endblock %}

frontend/admin_app/templates/admin_app_templates/change_password.html
{% extends 'admin_app_templates/base.html' %}
{% load static %}

{% block header %}

<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>




{% endblock %}

{% block title %}Change password{% endblock %}
{% block content %}

<div class="container">
    <div class="card bg-light mb-5" style="    margin-top: 88px;">
        <article class="card-body mx-auto" style="max-width: 400px;">
            <h4 class="card-title mt-3 text-center">Change Password</h4>
            <div class="form-group input-group">

                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                    </div>
                    <input class="form-control" placeholder="Old password" type="password" name="old_password">
                </div> <!-- form-group// -->
                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                    </div>
                    <input class="form-control" placeholder="New password" type="password" name="new_password">
                </div> <!-- form-group// -->
                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                    </div>
                    <input class="form-control" placeholder="Confirm password" type="password" name="confirm_password">
                </div> <!-- form-group// -->
                <div class="form-group ">
                    <button type="submit" class="btn btn-primary btn-block"> Save Changes </button>
                </div> <!-- form-group// -->

            </div>

        </article>
    </div> <!-- card.// -->

</div>



{% endblock %}

frontend/common/templates/common_templates/admin_login.html
{% extends 'common_templates/base.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/style_register.css' %}">
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<style>
    a {
        text-decoration: none;
    }

    .login-page {
        width: 100%;
        height: 100vh;
        display: inline-block;
        display: flex;
        align-items: center;
    }

    .form-right i {
        font-size: 100px;
    }
</style>

{% endblock %}

{% block title %}AdminLogin{% endblock %}
{% block content %}


<section>
    <div class="container-fluid">
        <div class="row">
            <div class="login-page bg-light">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-10 offset-lg-1">

                            <div class="bg-white shadow rounded">
                                <div class="row">
                                    <div class="col-md-7 pe-0">
                                        <div class="form-left h-100 py-5 px-5">
                                            <form action="" class="row g-4">
                                                <div class="col-12">
                                                    <label>Username<span class="text-danger">*</span></label>
                                                    <div class="input-group">
                                                        <div class="input-group-text"><i class="bi bi-person-fill"></i>
                                                        </div>
                                                        <input type="text" class="form-control" id="username"
                                                            placeholder="Enter Username">
                                                    </div>
                                                </div>

                                                <div class="col-12">
                                                    <label>Password<span class="text-danger">*</span></label>
                                                    <div class="input-group">
                                                        <div class="input-group-text"><i class="bi bi-lock-fill"></i>
                                                        </div>
                                                        <input type="text" class="form-control" id="password"
                                                            placeholder="Enter Password">
                                                    </div>
                                                </div>
                                                <span id="span1" style="color: brown;"></span>






                                                <div class="col-12">
                                                    <button type="button" id="subBtn"
                                                        class="btn btn-primary px-4">login</button>
                                                </div>
                                                <div class="col- text-center">
                                                    <p class="question">Don't have an account?</p>
                                                    <a class="createAcc" href="{% url 'common:admin_register' %}">Create an
                                                        account.</a>

                                                </div>

                                            </form>
                                        </div>
                                    </div>

                                    <div class="col-md-5 ps-0 d-none d-md-block">
                                        <div class="form-right h-100 bg-primary text-white text-center pt-5">
                                            <i class="bi bi-person-circle"></i>
                                            <h2 class="fs-1">Admin Login</h2>
                                        </div>
                                    </div>

                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>




<script>
    $(document).ready(function () {
        $('#subBtn').click(function () {
            admin_email = $('#username').val()
            admin_password = $('#password').val()
            console.log(admin_email, admin_password)
            $.ajaxSetup({
                headers: {
                    "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val() //passing csrf token in ajax request
                }
            })

            $.ajax({
                url: 'http://localhost:9000/common/admin_login/',
                data: {
                    'username': admin_email,
                    'password': admin_password
                },
                type: 'POST',
                success: function (response) {
                    console.log(response.status)
                    if (response.status == true) {
                        localStorage.setItem('token', response.token)

                        window.location.href = 'http://127.0.0.1:8000/admin_app/admin_dashboard/';

                    }
                    else {
                        $('#span1').html('email or password not match')
                    }
                },

            });
        })
    })
</script>




{% endblock %}

frontend/common/templates/common_templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- icon link -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">


    <!-- jquery cdn -->
    <script src="https://code.jquery.com/jquery-3.6.3.js"
        integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
    <!-- razorpay  -->
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.3.js"
        integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>


    <style>
        body {
            font-family: 'Poppins', sans-serif;
            color: black;
        }

        #navbar {
            box-shadow: 0 3px 9px 3px rgba(0, 0, 0, 0.1);
            position: sticky;
            top: 0;
            z-index: 1;
            padding: .5rem .5rem;

        }

        .koko {
            color: rgba(165, 42, 42, 0.938);

        }

        #navbarNav a {
            border-bottom: 2px solid transparent;
            color: black;

        }

        #navbarNav a:hover {
            border-bottom: 2px solid rgba(165, 42, 42, 0.938);
            color: black;

        }

        #navbarNav i:hover {
            color: rgba(165, 42, 42, 0.938);


        }

        footer {
            background-color: #e9ebed !important;
        }
    </style>
    {% block header %}

    {% endblock %}
    <title>{% block title %}base{% endblock %}</title>
</head>

<body>

    <body id="ll">
        <!-- navbar -->
        <nav class="navbar navbar-expand-lg bg-light " id="navbar">
            <div class="container-fluid">
                <a class="navbar-brand fw-bold fs-2" href="#"><span class="koko">Tourism Management</span> </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-expanded="false">
                    <span class="navbar-toggler-icon "><i class="bi bi-list"></i></span>
                </button>
                <div class="collapse navbar-collapse " id="navbarNav">
                    <ul class="navbar-nav fw-bold mx-auto" id="list">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="" style="color: brown;">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'common:about' %}" style="color: black;">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'common:blog' %}" style="color: black;">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'common:contact' %}" style="color: black;">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'common:customer_login' %}" style="color: black;">Login</a>
                        </li>
                        <!-- <li class="nav-item ms-5">
                            <form class="d-flex" method="">

                                <input class="form-control me-2 " type="search" placeholder="Search product"
                                    aria-label="Search" id="searchdata" name="searchdata">
                                <button class="btn btn-outline-dark" type="type" id="searchbtn"
                                    style="background-color: rgb(189, 68, 68);color: white;"><i
                                        class="bi bi-search"></i></button>

                            </form>
                            <div class="serch" id="search">

                               
                            </div>
                        </li> -->

                    </ul>
                    <div class="ms-3">


                        <a href="" type=" button " class="btn"><i class="bi bi-cart-fill"></i></a>

                        <a href="{% url 'common:admin_login' %}" type="button" class="btn"><i class="bi bi-person-fill">Admin Login</i></a>
                        <a href="" type="button" class="btn text-danger"><i class="bi bi-box-arrow-right"></i></a>


                    </div>
                </div>
            </div>
            </div>
        </nav>


        {% block content %}{% endblock %}

        <!-- Footer Section -->

        <footer class="mt-5 pt-5 pb-3" id="footer">
            <div class="container text-center text-md-start">
                <div class="row ">
                    <div class="col-lg-4 col-md-4 col-sm-6">
                        <h5><span class="koko">Tourism Management</h5>
                        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ducimus, unde? Et, facere?
                            Distinctio officia, pariatur eos ipsa tenetur veniam sapiente! Aut ipsam dicta, numquam
                            repudiandae natus expedita alias deserunt. Quam?</p>
                    </div>
                    <!-- <div class="col-lg-3 col-md-3 col-sm-6">
                        <h5>PRODUCTS</h5>
                        <p><a href=""></a>Dates</p>
                        <p><a href=""></a>Dry Fruit</p>
                        <p><a href=""></a>Chocolates</p>
                        <p><a href=""></a>Nuts</p>
                    </div> -->
                    <div class="col-lg-4 col-md-4 col-sm-6">
                        <h5>LINKS</h5>
                        <p><a href=""></a>Home</p>
                        <p><a href=""></a>Blog</p>
                        <p><a href=""></a>About Us</p>
                        <p><a href=""></a>Contact Us</p>
                        <p><a href=""></a>Terms & Conditions</p>

                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-6">
                        <h5>CONTACT</h5>
                        <p><i class="bi bi-house-fill"></i> Calicut,kerala</p>
                        <p><i class="bi bi-envelope-fill"></i>tourism@gmail.com</p>
                        <p><i class="bi bi-phone-fill"></i>+91 9645312745</p>
                        <p><i class="bi bi-printer-fill"></i>+33 2123215</p>

                    </div>

                </div>
                <hr class="mb-4">
                <div class="row">
                    <div class="col-lg-7 col-sm-12">
                        <p>copyright 2020 reserved by:<strong>Tourism management</strong></p>
                    </div>
                    <div class="col-lg-4 col-sm-12">
                        <ul class="list-unstyled list-inline">
                            <li class="list-inline-item"><a href="" class="btn-sm" style="font-size: 25px;"><i
                                        class="bi bi-facebook"></i></a></li>
                            <li class="list-inline-item"><a href="" class="btn-sm" style="font-size: 25px;"><i
                                        class="bi bi-whatsapp"></i></a></li>

                            <li class="list-inline-item"><a href="" class="btn-sm" style="font-size: 25px;"><i
                                        class="bi bi-twitter"></i></a></li>

                            <li class="list-inline-item"><a href="" class="btn-sm" style="font-size: 25px;"><i
                                        class="bi bi-linkedin"></i></a></li>

                        </ul>
                    </div>
                </div>
            </div>
        </footer>



    </body>




    </script>
    <script rel="stylesheet" href="{% static '/bootstrap/bootstrap.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>

</html>